version: "3.4"
services:
    publicapi:
        image: ${DOCKER_REGISTRY-}publicapi
        container_name: publicapi
        build:
            context: .
            dockerfile: PublicApi/Dockerfile           
        depends_on:
            - "db"
        ports:
         - "80:80"
    #db:
    #    image: postgres
    #    restart: always
    #    environment:
    #      POSTGRES_PASSWORD: example

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
    db:
        image: "postgres" # use latest official postgres version
        environment:
            POSTGRES_DB: MagShopDB
            POSTGRES_USER: <p@SSw0rd34>
            POSTGRES_PASSWORD: misha
        ports:
            - "5432:5432"