version: "3.4"
services:
    publicapi:
        image: ${DOCKER_REGISTRY-}publicapi
        container_name: publicapi
        build:
            context: .
            dockerfile: PublicApi/Dockerfile
        ports:
         - "8000:80"
        extra_hosts:
         - "host.docker.internal:172.17.0.1/16"