version: "3.4"
services:
    publicapi:
           image: ${DOCKER_REGISTRY-}publicapi
           build:
                context: .
                dockerfile: PublicApi/Dockerfile
           ports:
              - "5098:80"
           depends_on:
              - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "<p@SSw0rd34>"
            ACCEPT_EULA: "Y"
        ports:
         - "1433:1433"