version: "3.4"
services:
    publicapi:
        image: ${DOCKER_REGISTRY-}publicapi
        container_name: publicapi
        build:
            context: .
            dockerfile: PublicApi/Dockerfile           
        depends_on:
            - "db"
        ports:
         - "8000:80"

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
    db:
        image: "postgres" # use latest official postgres version
        environment:
            POSTGRES_DB: MagShopDB
            POSTGRES_USER: misha
            POSTGRES_PASSWORD: <p@SSw0rd34>
        ports:
            - "5432:5432"