version: "3.4"
services:
    publicapi:
        image: ${DOCKER_REGISTRY-}publicapi
        container_name: publicapi
        build:
            context: .
            dockerfile: PublicApi/Dockerfile
        ports:
         - "8000:80"