# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Azure Web App Docker - magaz-shop

on:
  push:  
    paths-ignore:
    - 'KursFinderParser/**'
    - 'ProductRecommender/**'
    - 'DB/**'
    - 'Web/**'
    - '.github/workflows/**'
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_RESOURCE_GROUP: rg-todo-sample  # target resource, must match the {resource-group-name} you setup in the pre-requisties
  WEB_API_NAME: PublicApi       # set the name for the Web Api on Azure
  CONTAINER_IMAGE_NAME: publicapi # set the name for the container image
  #SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}  # connection string for the Azure SQL database -> must be in the secrets
  REPO: ${{ secrets.AzureAppService_ContainerUsername_5ad7eea8a9c943eca1f068bf3cde2ef3 }}/publicapi

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: downcase REPO
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://publicapi20220226161756.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5ad7eea8a9c943eca1f068bf3cde2ef3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_70fc71d7e3f942fb93d82f15bb1f877c }}

    - run: |
       echo "REPO=$${{ secrets.AzureAppService_ContainerUsername_5ad7eea8a9c943eca1f068bf3cde2ef3,, }}" >>${GITHUB_ENV}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true        
        tags: publicapi20220226161756.azurecr.io/${{ env.REPO }}:${{ github.sha }}
        file: ./PublicApi/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'magaz-shop'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0fbfc365840d4e1a9ca0013c980a97cb }}
        images: 'publicapi20220226161756.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5ad7eea8a9c943eca1f068bf3cde2ef3 }}/publicapi:${{ github.sha }}'
