# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Selectel Web App Docker - magaz-shop

on:
  push:  
    paths-ignore:
    - 'KursFinderParser/**'
    - 'ProductRecommender/**'
    - 'DB/**'
    - 'Web/**'
    - '.github/workflows/**'
    branches:
      - main
  workflow_dispatch:
  
env:
  AZURE_RESOURCE_GROUP: rg-todo-sample  # target resource, must match the {resource-group-name} you setup in the pre-requisties
  WEB_API_NAME: PublicApi       # set the name for the Web Api on Azure
  CONTAINER_IMAGE_NAME: publicapi # set the name for the container image
  #SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}  # connection string for the Azure SQL database -> must be in the secrets

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: cr.selcloud.ru
        username: token
        password: ${{ secrets.container_registry_password }}
        
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true        
        tags: cr.selcloud.ru/magaz-shop
        file: ./PublicApi/Dockerfile
